yatube_project/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_posts'),
    path('group_list.html', views.group_list, name='group_list')
]

yatube_project/yatube_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls)
]

yatube_project/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, verbose_name='URL')
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )

yatube_project/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group


def index(request):
    template = 'posts/index.html'
    title = 'Это главная страница проекта Yatube'
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'title': title,
        'posts': posts
    }
    return render(request, template, context)


def group_list(request):
    template = 'posts/group_list.html'
    title = 'Здесь будет информация о группах проекта Yatube'
    context = {
        'title': title
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube_project/templates/base.html
{% include 'includes/header.html' %}
 <body>
      {% block content %}
      {% endblock %}
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube_project/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>

yatube_project/templates/includes/header.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    {%block title%}    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img\fav\favicon.ico' %}" type="image" >
    <link rel="apple-touch-icon" sizes="180x180" "{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" "{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" "{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{{title}}</title>
    {%endblock%}
  </head>
  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href={% url 'posts:index' %}>
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>
    </header>        

yatube_project/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{%include 'includes/header.html'%}
<main>    
{%block content%}
  <div class="container py-5">
    <h1>{{group.title}}</h1>
      <article>
        {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>    
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      </article>
  </div>
{%endblock%}
</main>  
{% include 'includes/footer.html' %} 

yatube_project/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{%include 'includes/header.html'%}
<main>
  {%block content%} 
    <div class="container py-5">     
    <h1>{{title}}</h1>
    <article>
      {% for post in posts %}
          <ul>
             <li> Автор: {{ post.author.get_full_name }} </li>
             <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
             </li>
          </ul>
          <p>{{ post.text }}</p>
          {% if post.group %}   
             <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
          {% endif %}
    </article>
          {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
  {%endblock%}
    </div>  
</main>        
      {% include 'includes/footer.html' %}
      